### ISSUE TITLE
Workflows - Test large data sets for workflows (metaMAGs)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaMAGs#1]
create a large test data set with expected outcome if workflow run is successful

link test results to this issue

**Comment by hubin-keio** [comment]
Will be tested at SDSC once the system (Cromwell etc.) is set up. Likely to get started near the last week of the Sprint.

**Comment by ssarrafan** [comment]
Closing per Bin's noted that this is done.
