### ISSUE TITLE
Review updates to MAGS workflow and update nmdc schema accordingly.

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/metaMAGs#11]

**Comment by Michal-Babins** [comment]
MAGs enums need to be reviewed before finalizing mags workflow for automation updates.

**Comment by scanon** [comment]
Agreed.  I have a branch of the schema that I'm trying to collect all of these changes in to.

**Comment by ssarrafan** [comment]
@Michal-Babins @scanon can this be moved to the next sprint beginning Oct 24th?  Do you plan on working on this the rest of the month?
