### ISSUE TITLE
Workflows - Test small data sets for workflows (metaMAGs)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaMAGs#2]
create a small test data set with expected outcome if workflow run is successful

link test results to this issue

**Comment by hubin-keio** [comment]
Chien-chi, please point me the location of two test data sets (one smaller set for quick test and one small realistic data set for thorough test) and the expected outcome from each workflow run in JSON format. Thank you.

**Comment by ssarrafan** [comment]
> Chien-chi, please point me the location of two test data sets (one smaller set for quick test and one small realistic data set for thorough test) and the expected outcome from each workflow run in JSON format. Thank you.

@chienchi not sure if you saw @hubin-keio's  last comment on this.  Can this issue be closed?  Or should I move it to the May sprint?

**Comment by chienchi** [comment]
commit 1cf6ffa
