### ISSUE TITLE
remove JGI mbin files from Docker folder

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaMAGs#25]
We do not have permission to distribute these files, they were added with commit id 14ec4dafe468223854332a8664364f88d852cdcb in June 2023. I have removed them in the master branch. We either need to update the mbin_nmdc task in the wdl such that it only requires Neha's container, njvarghese/mbin:v0.4, or we need to work with Neha to include mbin_stats.py, which I believe is NMDC code, in a new version of the container.

**Comment by aclum** [comment]
We are expecting an updated container from Neha that has the eukcc component shortly so we may want to combine these updates.

**Comment by ssarrafan** [comment]
Appears to be active. Will move to next sprint for completion.  FYI @chienchi @aclum

**Comment by aclum** [comment]
This is the container we should use library.jgi.doe.gov:5050/metagenome-science-program/mbin-docker:v1.0

Neha is making her dockerhub private shortly so we shouldn't use containers from dockerhub's njvarghese namespace.
