### ISSUE TITLE
Add support for passing a contig name mapping file to mbin.py

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaMAGs#29]
When NMDC runs workflows where the assembly was generated at JGI the binning workflow needs a mapping file to convert between the assembly fasta file and annotation files. We need to update the workflow such that there is an option to specify --map <mapping tsv file>

related to https://github.com/microbiomedata/metaMAGs/issues/26

Files that can be used to test this:
https://data.jgi.doe.gov/search?q=1414320&expanded=IMG_AP-1414320

assembly file: assembly.contigs.fasta
mapping file: Ga0597049_contig_names_mapping.tsv

**Comment by chienchi** [comment]
add --map option not work on `assembly file: assembly.contigs.fasta` but work on 
`assembly file: Ga0597049_contigs.fna` 

with map file, the mbin.py workflow will convert the depth coverage info generated from pairedMapped.sam.gz with correct ID.
