### ISSUE TITLE
eukCC failed on quoted node names.

### ISSUE THREAD

**Issue by chienchi** [microbiomedata/metaMAGs#32]
```
/pscratch/sd/n/nmdcda/cromwell-executions/nmdc_mags/f859549b-b820-48f7-ae8d-c1e8abacd6e2/call-mbin_nmdc/execution
```

raise NewickError("Unexpected newick format '%s' " %subnw[0:50]) ete3.parser.newick.NewickError: Unexpected newick format ''nmdc:wfmgas-11-wpm64z83.1_scf_321_c1_2':0.423943'

**Comment by aclum** [comment]
Thanks for making this ticket @chienchi I've asked Neha if she can update the her workflow to address this issue by specifying quoted_node_names=True

linking in the github issue you found earlier https://github.com/etetoolkit/ete/issues/194
