### ISSUE TITLE
total bases and gene counts issues

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaMAGs#49]
These are null in the sdb file, b/c they are generated in a downstream step in the JGI workflow, as currently written this would get propagated to mongo via the json. Please update mbin_stats.py to calculate these on fly for json file that is output.

**Comment by chienchi** [comment]
Total bases can be counted with the bins fasta files.  The gene count will need to wait till `task package` step when each bin linked with associated annotation files.  So, the both total base and gene count function will be better to add in the `create_tarfiles.py` script and update the mags_stats.json file.
