### ISSUE TITLE
Extract phylum data from MAG to support taxonomic search

### ISSUE THREAD

**Issue by hubin-keio** [microbiomedata/metaMAGs#6]

**Comment by ssarrafan** [comment]
@scanon and @hubin-keio should this issue be closed, moved to the backlog or moved to the October sprint?

**Comment by hubin-keio** [comment]
Please put it to October. Thanks!

**Comment by ssarrafan** [comment]
Per the mid sprint check-in and @emileyfadrosh suggestion, I'm moving this to the backlog.

**Comment by ssarrafan** [comment]
@hubin-keio can this issue be closed?

**Comment by chienchi** [comment]
I think we have capture the GTDBTK tax result in the stats.json file. 
example
https://nmdc-edge.org/projects/IxvDmVpbVHIP50MA/output/MetagenomeMAGs/7_2023_mags_stats.json

**Comment by chienchi** [comment]
close for the long standing issue and could be re-opened if comment above doesn't address the issue.
